# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trading.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'trading.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtrading.proto\x12\x07trading\"\xe3\x01\n\x0cTradeRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0c\n\x04side\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x12\n\norder_type\x18\x05 \x01(\t\x12\x1a\n\x12slippage_tolerance\x18\x06 \x01(\x01\x12\x35\n\x08metadata\x18\x07 \x03(\x0b\x32#.trading.TradeRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xda\x01\n\rTradeResponse\x12\x10\n\x08trade_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x16\n\x0e\x65xecuted_price\x18\x03 \x01(\x01\x12\x17\n\x0f\x65xecuted_amount\x18\x04 \x01(\x01\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12\x36\n\x08metadata\x18\x06 \x03(\x0b\x32$.trading.TradeResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"&\n\x12OrderStatusRequest\x12\x10\n\x08trade_id\x18\x01 \x01(\t\"\xe3\x01\n\x13OrderStatusResponse\x12\x10\n\x08trade_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rfilled_amount\x18\x03 \x01(\x01\x12\x15\n\raverage_price\x18\x04 \x01(\x01\x12\r\n\x05\x65rror\x18\x05 \x01(\t\x12<\n\x08metadata\x18\x06 \x03(\x0b\x32*.trading.OrderStatusResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xf6\x01\n\x0fTradingExecutor\x12?\n\x0c\x45xecuteTrade\x12\x15.trading.TradeRequest\x1a\x16.trading.TradeResponse\"\x00\x12M\n\x0eGetOrderStatus\x12\x1b.trading.OrderStatusRequest\x1a\x1c.trading.OrderStatusResponse\"\x00\x12S\n\x12MonitorOrderStatus\x12\x1b.trading.OrderStatusRequest\x1a\x1c.trading.OrderStatusResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trading_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRADEREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_TRADEREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TRADERESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_TRADERESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ORDERSTATUSRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_ORDERSTATUSRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_TRADEREQUEST']._serialized_start=27
  _globals['_TRADEREQUEST']._serialized_end=254
  _globals['_TRADEREQUEST_METADATAENTRY']._serialized_start=207
  _globals['_TRADEREQUEST_METADATAENTRY']._serialized_end=254
  _globals['_TRADERESPONSE']._serialized_start=257
  _globals['_TRADERESPONSE']._serialized_end=475
  _globals['_TRADERESPONSE_METADATAENTRY']._serialized_start=207
  _globals['_TRADERESPONSE_METADATAENTRY']._serialized_end=254
  _globals['_ORDERSTATUSREQUEST']._serialized_start=477
  _globals['_ORDERSTATUSREQUEST']._serialized_end=515
  _globals['_ORDERSTATUSRESPONSE']._serialized_start=518
  _globals['_ORDERSTATUSRESPONSE']._serialized_end=745
  _globals['_ORDERSTATUSRESPONSE_METADATAENTRY']._serialized_start=207
  _globals['_ORDERSTATUSRESPONSE_METADATAENTRY']._serialized_end=254
  _globals['_TRADINGEXECUTOR']._serialized_start=748
  _globals['_TRADINGEXECUTOR']._serialized_end=994
# @@protoc_insertion_point(module_scope)
